// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRG2SDGLfL01fonQTQOkrgbMibCODM230',
    appId: '1:644625826173:android:17ee9ad5b952cb25408c14',
    messagingSenderId: '644625826173',
    projectId: 'todoapp-854c5',
    storageBucket: 'todoapp-854c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0DGAGM-COPVgoJeQjKR8JHsXOS2OcLsg',
    appId: '1:644625826173:ios:520005326052d8db408c14',
    messagingSenderId: '644625826173',
    projectId: 'todoapp-854c5',
    storageBucket: 'todoapp-854c5.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJlwWCVNUDdYOu1OQ6NryEZWpA68PLWKQ',
    appId: '1:644625826173:web:c72d13aad8e06db7408c14',
    messagingSenderId: '644625826173',
    projectId: 'todoapp-854c5',
    authDomain: 'todoapp-854c5.firebaseapp.com',
    storageBucket: 'todoapp-854c5.firebasestorage.app',
  );
}
